name: Docs

on: push

jobs:
  create_docs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'

      - name: Retrieve the cached docs "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache-docs
        with:
          path: docs/node_modules
          key: node-modules-cache-${{ runner.os }}-${{ hashFiles('docs/package-lock.json') }}

      - name: Install docs dependencies (if the cached directory was not found)
        if: steps.node-cache-docs.outputs.cache-hit != 'true'
        run: cd ./docs && npm ci

      - name: Create the docs directory locally in CI
        run: cd ./docs && npm run build

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
