name: Docs

on: push

jobs:
  create_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy redirect
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.5.0
        with:
          branch: gh-pages
          folder: redirect
          clean: true
